DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 4
  TEST:
    BATCH_SIZE: 16
  NUM_WORKERS: 1

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.0035
  MAX_EPOCH: 20  # 测试（5）和训练(20)时候注意改回来 5历元设置分别适用于Food101、ImageNet的1/2/4和SUN397的1/2镜头
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 1 # 测试（5）和训练(20)时候注意改回来

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  CMPA:
    N_CTX: 16
    CTX_INIT: "a photo of a"
    PREC: "fp16"
    PROMPT_DEPTH: 9
